---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - windows_amd64
      - windows_386
      - windows_arm64
      - linux_amd64
      - linux_386
      - linux_arm64
      - linux_arm_7
      - linux_arm_6
      - linux_mipsle
      - darwin_amd64
      - darwin_arm64
    flags:
      - trimpath
    ldflags:
      - -s
      - -w

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
